spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
